### PR TITLE
feat: copy add alignment

### PR DESCRIPTION
**Pull request by lambdaclan**
# Adjust `COPY` instruction to be in line with `ADD` instruction

⚠️NOTE⚠️
---
- The proposed changes introduce **breaking changes** as they alter the recipe structure meaning that existing recipes will no longer build without adopting the new style.

## Description

This PR adjusts the `COPY` command structure to be in line with the similar `ADD` command. This ensures consistency and closely emulates how raw Dockerfiles work.

### Proposed Changes

- Update `Copy` structure to use a map to specify source and destination
- Remove the unecessary `Path` structure 
- Update recipe structure documentation

#### Before

```yml
copy:
      - workdir: /tmp
        from: build
        paths:
          - src: /app/awesome.txt
            dst: .
          - src: /tmp/test.txt
            dst: .
      - workdir: /etc
        paths:
          - src: /app/hello.txt
            dst: .
```

#### After

```yml
copy:
      - workdir: /tmp
        from: build
        srcdst:
          /app/awesome.txt: .
          /tmp/test.txt: .
      - workdir: /etc
        srcdst:
            /app/hello.txt: .
```

### Local Testing

Using the following `vib.yml` recipe:

```yml
name: Copy Add Example
id: copy-add-example
stages:
  - id: build
    base: node:lts
    singlelayer: false
    labels:
      maintainer: Vanilla OS Contributors
    adds:
      - workdir: /tmp/user/files
        srcdst:
          go.mod: .
      - workdir: /tmp/otheruser/files
        srcdst:
          go.mod: .
          go.sum: .
    copy:
      - workdir: /tmp
        from: build
        srcdst:
          /app/awesome.txt: .
          /tmp/test.txt: .
      - workdir: /etc
        srcdst:
          /app/hello.txt: .
```

```sh
vib build vim.yml
```

example

Generated Containerfile:

```dockerfile
# Stage: build
FROM node:lts AS build
WORKDIR /tmp
COPY --from=build /app/awesome.txt .
COPY --from=build /tmp/test.txt .
WORKDIR /
WORKDIR /etc
COPY /app/hello.txt .
WORKDIR /
LABEL maintainer='Vanilla OS Contributors'
WORKDIR /tmp/user/files
ADD go.mod .
WORKDIR /
WORKDIR /tmp/otheruser/files
ADD go.mod .
ADD go.sum .
WORKDIR /
ADD includes.container /
ADD sources /sources
```

### CODE REVIEW

**Comment by lambdaclan** [comment]
I feel we need to bump the version of Vib to reflect the new overall structure including the previously merged workdir changes. Please let me know what you think.

Thank you!

**Comment by taukakao** [comment]
While I preferred the syntax of copy over that of add I think it's too late to change this now. 
So this change is ok with me.

And yes, I agree that this should be a new vib version.

**Comment by lambdaclan** [comment]
Hello Tau.

> While I preferred the syntax of copy over that of add I think it's too late to change this now either way.
So this change is ok with me.

I went with the ADD syntax because it is simpler (less typing) and behaves more like an actual Dockerfile.
Saying that, I do not want to impose anything so if the team prefers the original COPY syntax please let me know. I will be happy to do the necessary changes.

**Comment by taukakao** [comment]
> if the team prefers the original COPY syntax please let me know

It's just my personal opinion. I guess we can wait if other people have an opinion as well. 
But as I said, I think this is fine.

**Review by mirkobrombin — APPROVED** [review]
LGTM

**Review by taukakao — APPROVED** [review]
LGTM

**Review by kbdharun — APPROVED** [review]
LGTM, Thanks for your contribution. Tested and verified the changes locally.

**Pull request merged**
