### PR TITLE
fix/53 Building a container image without a recipe name throws error

### PR DESCRIPTION
**Pull request by deepu9**
This will let the users to run `vib build` with a recipe yml file in the folder. You can still provide the recipe name in the command, that's still the recommended way.

In addition to this fix, I have also added the following validation:
1. file check to see whether the provided recipe path exists.
2. extension check for either yml or yaml.

It's best to catch errors early in **cmd** than to leave to other packages.

It is also recommended to use `errors.Is(...)` instead of `os.Is(...)`. Refer to the following golang issue

https://github.com/golang/go/issues/41122

### CODE REVIEW

**Comment by matbme** [comment]
Thanks for the contribution! Once you fix the typo above, could you please rebase everything in a single commit?

**Review by matbme — APPROVED** [review]
LGTM

**Review by kbdharun — COMMENTED** [review]
LGTM, thanks for your contribution. (Forgot to approve 😅 while rebasing)

**Comment by deepu9** [comment]
Sorry @matbme, I went to bed and didn't get a chance to fix it.

Thanks @kbdharun

**Pull request merged**
